### PR TITLE
jsdoc object generator function

### PR DESCRIPTION
**Pull request by mxab**
Hi,
I started to work on a jsdoc type generator function within simple schema, so it can be used to print out the type of a schema that you later want to use in a @type{....} annotation for example

see this example https://github.com/mxab/simple-schema-jsdoc-example

### CODE REVIEW

**Comment by aldeed** [comment]
@mxab I am thinking whether this might be better as an add-on package.

**Comment by mxab** [comment]
@aldeed sure makes sense
here you go ```mxab:simple-schema-jsdoc```
I also rewrote it

**Comment by aldeed** [comment]
Thanks. I added a link in the readme.

**Comment by mxab** [comment]
cool!

**Pull request closed without merging**
