### PR TITLE
Fix whitespace strings

### PR DESCRIPTION
**Pull request by wursttheke**
Fixes an issue with whitespace only strings not being cleaned out.

### CODE REVIEW

**Comment by wursttheke** [comment]
Oh, sorry Eric. I didn't mean to send this PR to your master branch. I made this fix in the devel branch. Maybe that's why a commit of yours made it into this PR. Strange. :)

This fixes the problem described in https://github.com/aldeed/meteor-simple-schema/issues/140#issuecomment-75927292.

But I discovered that empty strings actually pass validation (without cleaning):

```javascript
mySchema = new SimpleSchema({
  name: { type: String },
});

Match.test({ name: "" }, mySchema); // returns true
```

Is this intended behavior? IMO if a field is required, an empty string shouldn't pass validation.

**Comment by aldeed** [comment]
Yes, empty strings should be considered a valid entry for required fields. At one point they were not but we changed that some time ago because several people wanted to be able to store an empty string. I personally do not see the point, but that's why we clean first, so if you don't want empty strings to pass validation, you just need to do `removeEmptyStrings` validation and then they won't pass requiredness check.

I'll review this when I have some time.

**Comment by aldeed** [comment]
Also, I think you can still change this PR to point to `devel` without doing a new one. Maybe not though.

**Comment by wursttheke** [comment]
I'll quickly create a new one. :)

**Pull request closed without merging**
