### PR TITLE
Add hashmap objects validation

### PR DESCRIPTION
**Pull request by namirsab**
## What is this PR doing?

Is adding hashmap objects validation, in order to validate objects like this:

``` js
var schema = new SimpleSchema({
    obj: {
        type: Object,
        hashmap: true,
        fixedKeys: ['fixed1', 'fixed2']
    },
    'obj.*': {
        type: Object,
        hashmap: true,
        fixedKeys: ['deepFixed']
    },
    'obj.*.test': {
        type: Boolean,
    },
    'obj.*.deepFixed': {
        type: Object,
        hashmap: true  
    },
    'obj.*.deepFixed.*.aTest': {
        type: String
    },
    'obj.fixed1': {
        type: Number
    },
    'obj.fixed2': {
        type: [Number]
    }
});

var o = {
    obj: {
        key1: {
            test: true,
            deepFixed: {

            }
        },
        key2: {
            test: true,
            deepFixed: {
                key1: {
                }
            }
        },
        fixed1: 1,
        fixed2: [1,2,3,4] 
    }
};
```

It throws errros with the real keypath not with the generic one, just like arrays.

image

### CODE REVIEW

**Comment by algirdasp** [comment]
This addition seems incredibly useful for my schema aswell.

**Comment by namirsab** [comment]
It seem I have to fix some tests!

**Comment by s-ol** [comment]
+1, been searching through docs and issues to find something like this. Right now the only thing you can do is have a blackbox if you don't know in advance what the keys will be (Or bend your db to make the schema fit, like using an array and storing the key in the subdocuments).

**Comment by namirsab** [comment]
@s-ol i've created a PR for that issue :smile:

**Comment by s-ol** [comment]
@namirsab this is actually the PR's thread, not the issue's :P We might switch our codebase to your branch for the time being.

**Comment by namirsab** [comment]
@s-ol ups sorry!
Yeah, change it and tell me if you find any bugs! That would be wonderful
I'm using it **a lot** in my company, and it's workign right now without problems.
I maybe need to add some documentation, would you need that?

**Comment by s-ol** [comment]
@namirsab to get the PR merged maybe documentation in the README would help, our use case is rather minimal though; I think I can do without for now. Really all we need to do is attach a schema to all values on an object with arbitrary keys, I suppose that

```
const ValueSchema = new SimpleSchema({ required: { type: String } });
const Schema = new SimpleSchema({
  field: {
    type: Object,
    hashmap: true,
  },
  'field.*': {
    type: ValueSchema,
  },
});
```

would match

```
{
  field: {
    somekey: { required: "yes" },
    other: { required: "yes" },
  }
}
```

but not either of these:
```
{
  field: {
    somekey: { required: 3 },
  }
}

{
  field: {
    somekey: {},
  }
}
```

Also, I would suggest providing a more basic (less nested) example, perhaps leaving the one above as an "advanced" one.

**Comment by namirsab** [comment]
@s-ol yes, you are right. I will add the documentation.
Regarding your question, yes, that's the behaviour.
Any question please ask!  :smile:

**Comment by chrisbobbe** [comment]
This feature would be very useful for me too; is there a reason it hasn't moved forward?

**Pull request closed without merging**
